### ISSUE TITLE
Suddenly getting invalid_credentials

### ISSUE THREAD

**Issue by dznicol** [mkdynamic/omniauth-facebook#278] opened 2017-03-27 23:22 UTC
As of today I am always getting `invalid_credentials` my callback. The callback is of the format:

```
Started GET "/members/auth/facebook/callback?code=xyz&state=abc" for 127.0.0.1 at 2017-03-28 00:13:24 +0100
```

This is on my test system, production also fails as of today.

The error then is:

```
I, [2017-03-28T00:13:24.727498 #14723]  INFO -- omniauth: (facebook) Callback phase initiated.
E, [2017-03-28T00:13:24.998671 #14723] ERROR -- omniauth: (facebook) Authentication failure! invalid_credentials: OAuth2::Error, : 
{"access_token":".....","token_type":"bearer","expires_in":5171905}
Processing by OmniauthCallbacksController#failure as HTML
  Parameters: {"code"=>"xyz", "state"=>"abc"}
```

All tokens are there (just removed from this report).

I can't see any relevant recent updates in Gemfile.lock.

I am using:

```
    omniauth (1.3.1)
      hashie (>= 1.2, < 4)
      rack (>= 1.0, < 3)
    omniauth-facebook (3.0.0)
      omniauth-oauth2 (~> 1.2)
    omniauth-oauth2 (1.4.0)
      oauth2 (~> 1.0)
      omniauth (~> 1.2)
    devise (3.5.6)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 3.2.6, < 5)
      responders
      thread_safe (~> 0.1)
      warden (~> 1.2.3)
```

All help, guidance or pointers as to where to look appreciated. I have searched high and low and debugged through the code but can't find anything specific.

David

**Comment by simi** [comment] 2017-03-27 23:23
Is this dupe of https://github.com/mkdynamic/omniauth-facebook/issues/276? Try to update to `omniauth-facebook ~> 4.0.0` at least.

**Comment by dznicol** [comment] 2017-03-27 23:32
Fixed.

Thank you simi!

David

**Comment by jay-pandya-btc** [comment] 2017-03-28 10:16
Thanks @simi i was facing the same problem for last 4 hours. :+1:

**Comment by dansteele** [comment] 2017-03-28 10:18
Fixed over here too :)

**Comment by n1ckbren** [comment] 2017-03-28 12:30
It doesn't work for updating from 2.0.1 to 4.0.0. What do I have to do for upgrading?
Now I have: 
  * omniauth (1.6.1)
  * omniauth-facebook (4.0.0)
  * omniauth-oauth2 (1.4.0)
A

**Comment by codeodor** [comment] 2017-03-28 12:35
We're seeing the same issue. Worked fine for the last 1+ year, and last night all of the sudden we're getting invalid credentials. 

Upgrading from 3 to 4 fixes it. (At least in dev mode, so I assume it will work in production now as well).

What changed?

**Comment by dimitridewit** [comment] 2017-03-28 12:51
Same problems here also. Updating to 4 seems to work on development here to. Although a peer dependency of another Gem, Hashie in this case, is giving me a conflicting key warning now.

**Comment by n1ckbren** [comment] 2017-03-28 13:02
I think I found something similar maybe it helps. https://github.com/isaacsanders/omniauth-stripe-connect/issues/44

**Comment by stevehodges** [comment] 2017-03-28 13:28
Here's what changed: Facebook API version 2.2 was EOL yesterday and turned off. See https://developers.facebook.com/docs/apps/changelog/ for Facebook's version availability schedule.

**Comment by n1ckbren** [comment] 2017-03-28 13:44
@stevehodges yes that doesn't help.


Finally I just restarted the server and now it's back doing just fine. Gotta love these issues, they come once a year, ruin everything and the fly away.

**Comment by Revokee** [comment] 2017-03-28 14:28
Confirming the fix as well.

**Closed** 2017-03-28 14:38 UTC

**Comment by chetanbissa27** [comment] 2017-03-28 17:07
@n1ckbren Please help me I am facing same issue and upgrading gem to 4.0.0 can broke other functionality on production. Is there any other to solve this issue except updating from 2.0.1 to 4.0.0.

**Comment by n1ckbren** [comment] 2017-03-28 18:32
@chetanbissa27 what do you do? let's write step by step.

**Comment by n1ckbren** [comment] 2017-03-28 18:43
@chetanbissa27 I think you broke app because all gems updated. Yo have to update only omniauth-facebook.

https://mozpi.com/articles/how-to-fix-invalid-credential-omniauth-facebook-gem-broken-after-facebook-api-deprecation-id-83

**Comment by jakeatwork** [comment] 2017-03-28 22:33
Ok...found a way without updating the gem, if you happen to be in a situation where updating a library is less than ideal:

You can add the following in your `config/initializers/devise.rb` file at the `config.omniauth` line:

    client_options: {
      site: "https://graph.facebook.com/v2.3",
      authorize_url: "https://www.facebook.com/v2.3/dialog/oauth"
    },
    token_params: {
      parse: :json
    }

YMMV with the full config, but it would look something like this:

    config.omniauth :facebook, ENV["FACEBOOK_KEY"], ENV["FACEBOOK_SECRET"],
        scope: 'email',
        secure_image_url: true,
        auth_type: 'https',
        info_fields: 'email,name,first_name,last_name',
        client_options: {
            site: "https://graph.facebook.com/v2.3",
            authorize_url: "https://www.facebook.com/v2.3/dialog/oauth"
        },
        token_params: {
            parse: :json
        }

The main issue is that they upgraded the response format and without the forced version pointer and the token params to parse the new json format (instead of url encoded format), it would break at the response because it didn't recognize what was spit back from the api.

**Comment by chetanbissa27** [comment] 2017-03-29 03:14
@n1ckbren Thank you I was doing same thing but due to dependencies updates it broked.
@jakeatwork Thank you this solution worked but now new problem came up 
Dragonfly::DataStorage::UnableToStore (Permission denied - /var/dragonfly):

**Comment by echan00** [comment] 2017-04-11 05:35
Thank you a tonne. Kind of sucks that this broke all of a sudden, i have to say it took me a while to finally find this fix as well.

**Comment by raven-chen** [comment] 2017-05-03 07:49
I'm maintaining an old project which involves with oauth2, omniauth-facebook, twitter, weibo, rack-oauth-server...  upgrading is not a option for the project, so I patched `oauth2` to fix this problem. hope this could help someone like me 😄 

the commit is here https://github.com/raven-chen/oauth2/commit/58ec927a818844d5ea0093b3f101a24290081bc6. just force oauth2 to use JSON parser for facebook.

```ruby
      if response.env.url.to_s.include?('graph.facebook.com')
         @parsed ||= PARSERS[:json].call(body)
      else
         @parsed ||= PARSERS[parser].call(body)
      end
```

**Comment by Luna2442** [comment] 2017-11-14 20:46
Nothing working here. Same error as above. Using omniauth 4.0.0
