### ISSUE TITLE
secure_image_url not making any difference

### ISSUE THREAD

**Issue by MatthewMDavis** [mkdynamic/omniauth-facebook#237] opened 2016-04-26 18:53 UTC
Whether or not I set `secure_image_url` to `true`, I get no image and the following warning:

`Mixed Content: The page at 'https://fakeapp.herokuapp.com/#' was loaded over HTTPS, but requested an insecure image 'http://graph.facebook.com/10934827019283457/picture'. This content should also be served over HTTPS.`

This is running omniauth-facebook v3.0.0 and the Facebook API is v2.6.

**Comment by mkdynamic** [comment] 2016-06-27 00:53
@MatthewMDavis Can you paste our OmniAuth config? I cannot reproduce this and the unit test we have overing this suggests the option is used:
https://github.com/mkdynamic/omniauth-facebook/blob/master/test/strategy_test.rb#L98

If you are able to write a failing test case, that would be most appreciated.

**Comment by MatthewMDavis** [comment] 2016-06-27 00:59
I realized that the Facebook-linked accounts that weren't showing the
secure image were accounts created before I had turned that flag on.
Deleting the accounts and re-authorizing solved the problem.

**Comment by mkdynamic** [comment] 2016-06-27 01:14
K, thanks @MatthewMDavis that sounds like the culprit. Closing.

**Closed by mkdynamic** 2016-06-27 01:14 UTC
Labels: info-needed, patches-welcome

**Comment by tannerbrandt** [comment] 2016-08-10 19:16
Hey everyone - I have no idea why this happens to people once and awhile. I can't seem to trace it either, even when it works perfectly in one of our apps, but not in the other. Secure image is called correctly, but all the Facebook photos are returned, even when you call for only the one image size. There is a work around if you need it (until someone spots the issue)- simply call this when you create the user and upload the image using carrierwave: 

`:remote_profile_picture_url => auth.info.image.split("?")[0] << "?type=large"`
